obj-$(CONFIG_SND_STM) += snd-stm.o
snd-stm-y := init.o common.o synchro.o
snd-stm-$(CONFIG_CPU_SUBTYPE_STB7100) += stx710x.o
snd-stm-$(CONFIG_CPU_SUBTYPE_STX7111) += stx7111.o
snd-stm-$(CONFIG_CPU_SUBTYPE_STX7200) += stx7200.o
snd-stm-y += audio_outputs.o conv.o conv_dummy.o conv_i2s-spdif.o conv_internal_dac.o
snd-stm-y += fsynth.o pcm_player.o pcm_reader.o spdif_player.o
