obj-$(CONFIG_SND_STM) += snd-stm.o
snd-stm-y := init.o common.o synchro.o
snd-stm-$(CONFIG_CPU_SUBTYPE_STB7100) += stx710x.o
snd-stm-$(CONFIG_CPU_SUBTYPE_STX7200) += stx7200.o
snd-stm-y += audio_outputs.o dac.o dac_internal.o fsynth.o
snd-stm-y += i2s-spdif_converter.o pcm_player.o pcm_reader.o spdif_player.o
