#
# Makefile for aotom frontpanel controler of Fulan spark 71xx set-top boxes
#
# See the README file in this directory for more info. <k4230r6@gmail.com>
#

aotom-objs += aotom_trace.o
aotom-objs += aotom_i2csoft.o
aotom-objs += aotom_vfd.o
aotom-objs += aotom_main.o

obj-m += aotom.o
