#ifndef __STM_REGISTERS_STX710x_AUDCFG_H
#define __STM_REGISTERS_STX710x_AUDCFG_H



#define AUDCFG_IO_CTRL 0x00

#define AUDCFG_IO_CTRL__PCM_CLK_EN__SHIFT         0
#define AUDCFG_IO_CTRL__PCM_CLK_EN__MASK          0x1
#define AUDCFG_IO_CTRL__PCM_CLK_EN__VALUE__INPUT  0x0
#define AUDCFG_IO_CTRL__PCM_CLK_EN__VALUE__OUTPUT 0x1

#define AUDCFG_IO_CTRL__DATA0_EN__SHIFT         1
#define AUDCFG_IO_CTRL__DATA0_EN__MASK          0x1
#define AUDCFG_IO_CTRL__DATA0_EN__VALUE__INPUT  0x0
#define AUDCFG_IO_CTRL__DATA0_EN__VALUE__OUTPUT 0x1

#define AUDCFG_IO_CTRL__DATA1_EN__SHIFT         2
#define AUDCFG_IO_CTRL__DATA1_EN__MASK          0x1
#define AUDCFG_IO_CTRL__DATA1_EN__VALUE__INPUT  0x0
#define AUDCFG_IO_CTRL__DATA1_EN__VALUE__OUTPUT 0x1

#define AUDCFG_IO_CTRL__SPDIF_EN__SHIFT          3
#define AUDCFG_IO_CTRL__SPDIF_EN__MASK           0x1
#define AUDCFG_IO_CTRL__SPDIF_EN__VALUE__DISABLE 0x0
#define AUDCFG_IO_CTRL__SPDIF_EN__VALUE__ENABLE  0x1

#define AUDCFG_IO_CTRL__HDMI_AUD_SRC__SHIFT               4
#define AUDCFG_IO_CTRL__HDMI_AUD_SRC__MASK                0x1
#define AUDCFG_IO_CTRL__HDMI_AUD_SRC__VALUE__PCM_PLAYER   0x0
#define AUDCFG_IO_CTRL__HDMI_AUD_SRC__VALUE__SPDIF_PLAYER 0x1



#endif
