#ifndef __STM_REGISTERS_STX7111_AUDCFG_H
#define __STM_REGISTERS_STX7111_AUDCFG_H



#define AUDCFG_IO_CTRL 0x00

#define AUDCFG_IO_CTRL__PCM_CLK_EN__SHIFT         0
#define AUDCFG_IO_CTRL__PCM_CLK_EN__MASK          0x1
#define AUDCFG_IO_CTRL__PCM_CLK_EN__VALUE__INPUT  0x0
#define AUDCFG_IO_CTRL__PCM_CLK_EN__VALUE__OUTPUT 0x1

#define AUDCFG_IO_CTRL__SPDIFHDMI_EN__SHIFT         3
#define AUDCFG_IO_CTRL__SPDIFHDMI_EN__MASK          0x1
#define AUDCFG_IO_CTRL__SPDIFHDMI_EN__VALUE__INPUT  0x0
#define AUDCFG_IO_CTRL__SPDIFHDMI_EN__VALUE__OUTPUT 0x1

#define AUDCFG_IO_CTRL__PCMPLHDMI_EN__SHIFT         5
#define AUDCFG_IO_CTRL__PCMPLHDMI_EN__MASK          0x1
#define AUDCFG_IO_CTRL__PCMPLHDMI_EN__VALUE__INPUT  0x0
#define AUDCFG_IO_CTRL__PCMPLHDMI_EN__VALUE__OUTPUT 0x1

#define AUDCFG_IO_CTRL__CLKREC_SEL__SHIFT            9
#define AUDCFG_IO_CTRL__CLKREC_SEL__MASK             0x3
#define AUDCFG_IO_CTRL__CLKREC_SEL__VALUE__PCMPLHDMI 0x0
#define AUDCFG_IO_CTRL__CLKREC_SEL__VALUE__SPDIFHDMI 0x1
#define AUDCFG_IO_CTRL__CLKREC_SEL__VALUE__PCMPL1    0x2

#endif
