#
# Makefile for the STMicroelectronics device drivers.
#

obj-y				+= sysconf.o
obj-$(CONFIG_STM_DMA)		+= 710x_fdma2.o
obj-$(CONFIG_STM_PIO)		+= pio.o
obj-$(CONFIG_STM_SSC)		+= stm_ssc.o
obj-$(CONFIG_STM_SPI)		+= stm_spi.o
obj-$(CONFIG_STM_COPROCESSOR_SUPPORT)	+= copro-stb7100.o
obj-$(CONFIG_STM_COPROCESSOR)		+= stm-coprocessor.o
obj-$(CONFIG_STM_COPROCESSOR_FRMW)	+= stm-coprocessor_frmw.o
obj-y				+= emi.o
