#
# Makefile for STMicroelectronics STx7200 Mboard (mb519) board
#

obj-y := setup.o epld.o
obj-$(CONFIG_SH_ST_MB520) += mb520.o
obj-$(CONFIG_SH_ST_MB562) += mb562.o
epld-y := ../common/epld.o
mb520-y := ../common/mb520.o
mb562-y := ../common/mb562.o
