#
# Makefile for STMicroelectronics boards common implementation
#

obj-$(CONFIG_SH_ST_HARP_IRQ) += harp-irq.o
obj-$(CONFIG_SH_ST_EPLD) += epld.o

obj-$(CONFIG_SH_ST_DB641) += db641.o
obj-$(CONFIG_SH_ST_MB520) += mb520.o
obj-$(CONFIG_SH_ST_MB562) += mb562.o
obj-$(CONFIG_SH_ST_MB588) += mb588.o
