#ifndef __STM_REGISTERS_AUD_PCMIN_H
#define __STM_REGISTERS_AUD_PCMIN_H



#define AUD_PCMIN__RST 0x00

#define AUD_PCMIN__RST__RSTP__SHIFT 0
#define AUD_PCMIN__RST__RSTP__MASK  0x00000001



#define AUD_PCMIN__DATA 0x04

#define AUD_PCMIN__DATA__DATA__SHIFT 0
#define AUD_PCMIN__DATA__DATA__MASK  0xffffffff



#define AUD_PCMIN__ITS 0x08

#define AUD_PCMIN__ITS__OVF__SHIFT 0
#define AUD_PCMIN__ITS__OVF__MASK  0x00000001

#define AUD_PCMIN__ITS__VSYNC__SHIFT 1
#define AUD_PCMIN__ITS__VSYNC__MASK  0x00000001



#define AUD_PCMIN__ITS_CLR 0x0c

#define AUD_PCMIN__ITS_CLR__OVF__SHIFT 0
#define AUD_PCMIN__ITS_CLR__OVF__MASK  0x00000001

#define AUD_PCMIN__ITS_CLR__VSYNC__SHIFT 1
#define AUD_PCMIN__ITS_CLR__VSYNC__MASK  0x00000001



#define AUD_PCMIN__IT_EN 0x10

#define AUD_PCMIN__IT_EN__OVF__SHIFT 0
#define AUD_PCMIN__IT_EN__OVF__MASK  0x00000001

#define AUD_PCMIN__IT_EN__VSYNC__SHIFT 1
#define AUD_PCMIN__IT_EN__VSYNC__MASK  0x00000001



#define AUD_PCMIN__IT_EN_SET 0x14

#define AUD_PCMIN__IT_EN_SET__OVF__SHIFT 0
#define AUD_PCMIN__IT_EN_SET__OVF__MASK  0x00000001

#define AUD_PCMIN__IT_EN_SET__VSYNC__SHIFT 1
#define AUD_PCMIN__IT_EN_SET__VSYNC__MASK  0x00000001



#define AUD_PCMIN__IT_EN_CLR 0x18

#define AUD_PCMIN__IT_EN_CLR__OVF__SHIFT 0
#define AUD_PCMIN__IT_EN_CLR__OVF__MASK  0x00000001

#define AUD_PCMIN__IT_EN_CLR__VSYNC__SHIFT 1
#define AUD_PCMIN__IT_EN_CLR__VSYNC__MASK  0x00000001



#define AUD_PCMIN__CTRL 0x1c

#define AUD_PCMIN__CTRL__MODE__SHIFT 0
#define AUD_PCMIN__CTRL__MODE__MASK  0x00000003

#define AUD_PCMIN__CTRL__MEM_FMT__SHIFT 2
#define AUD_PCMIN__CTRL__MEM_FMT__MASK  0x00000001

#define AUD_PCMIN__CTRL__RND__SHIFT 3
#define AUD_PCMIN__CTRL__RND__MASK  0x00000001

#define AUD_PCMIN__CTRL__NUM_FRAMES__SHIFT 4
#define AUD_PCMIN__CTRL__NUM_FRAMES__MASK  0x0fffffff




#define AUD_PCMIN__STA 0x20

#define AUD_PCMIN__STA__RUN_STOP__SHIFT 0
#define AUD_PCMIN__STA__RUN_STOP__MASK  0x00000001

#define AUD_PCMIN__STA__OVF__SHIFT 1
#define AUD_PCMIN__STA__OVF__MASK  0x00000001

#define AUD_PCMIN__STA__SAMPL_CNT__SHIFT 2
#define AUD_PCMIN__STA__SAMPL_CNT__MASK  0x0000ffff

#define AUD_PCMIN__STA__VSYNC__SHIFT 18
#define AUD_PCMIN__STA__VSYNC__MASK  0x00000001

#define AUD_PCMIN__STA__NFRAMES__SHIFT 19
#define AUD_PCMIN__STA__NFRAMES__MASK  0x00000001



#define AUD_PCMIN__FMT 0x24

#define AUD_PCMIN__FMT__NBIT__SHIFT 0
#define AUD_PCMIN__FMT__NBIT__MASK  0x00000001

#define AUD_PCMIN__FMT__DATA_SIZE__SHIFT 1
#define AUD_PCMIN__FMT__DATA_SIZE__MASK  0x00000003

#define AUD_PCMIN__FMT__LR_POL__SHIFT 3
#define AUD_PCMIN__FMT__LR_POL__MASK  0x00000001

#define AUD_PCMIN__FMT__SCLK_EDGE__SHIFT 4
#define AUD_PCMIN__FMT__SCLK_EDG__MASK  0x00000001

#define AUD_PCMIN__FMT__PADDING__SHIFT 5
#define AUD_PCMIN__FMT__PADDING__MASK  0x00000001

#define AUD_PCMIN__FMT__ALIGN__SHIFT 6
#define AUD_PCMIN__FMT__ALIGN__MASK  0x00000001

#define AUD_PCMIN__FMT__ORDER__SHIFT 7
#define AUD_PCMIN__FMT__ORDER__MASK  0x00000001



#endif
