#ifndef __STM_REGISTERS_AUD_PCMIN_H
#define __STM_REGISTERS_AUD_PCMIN_H



#define AUD_PCMIN_RST 0x00

#define AUD_PCMIN_RST__RSTP__SHIFT          0
#define AUD_PCMIN_RST__RSTP__MASK           0x1
#define AUD_PCMIN_RST__RSTP__VALUE__RUNNING 0x0
#define AUD_PCMIN_RST__RSTP__VALUE__RESET   0x1



#define AUD_PCMIN_DATA 0x04

#define AUD_PCMIN_DATA__DATA__SHIFT 0
#define AUD_PCMIN_DATA__DATA__MASK  0xffffffff



#define AUD_PCMIN_ITS 0x08

#define AUD_PCMIN_ITS__OVF__SHIFT          0
#define AUD_PCMIN_ITS__OVF__MASK           0x1
#define AUD_PCMIN_ITS__OVF__VALUE__PENDING 0x1

#define AUD_PCMIN_ITS__VSYNC__SHIFT          1
#define AUD_PCMIN_ITS__VSYNC__MASK           0x1
#define AUD_PCMIN_ITS__VSYNC__VALUE__PENDING 0x1



#define AUD_PCMIN_ITS_CLR 0x0c

#define AUD_PCMIN_ITS_CLR__OVF__SHIFT        0
#define AUD_PCMIN_ITS_CLR__OVF__MASK         0x1
#define AUD_PCMIN_ITS_CLR__OVF__VALUE__CLEAR 0x1

#define AUD_PCMIN_ITS_CLR__VSYNC__SHIFT       1
#define AUD_PCMIN_ITS_CLR__VSYNC__MASK        0x1
#define AUD_PCMIN_ITS_CLR__VSYNC__VALUE_CLEAR 0x1



#define AUD_PCMIN_IT_EN 0x10

#define AUD_PCMIN_IT_EN__OVF__SHIFT           0
#define AUD_PCMIN_IT_EN__OVF__MASK            0x1
#define AUD_PCMIN_IT_EN__OVF__VALUE__DISABLED 0x0
#define AUD_PCMIN_IT_EN__OVF__VALUE__ENABLED  0x1

#define AUD_PCMIN_IT_EN__VSYNC__SHIFT           1
#define AUD_PCMIN_IT_EN__VSYNC__MASK            0x1
#define AUD_PCMIN_IT_EN__VSYNC__VALUE__DISABLED 0x0
#define AUD_PCMIN_IT_EN__VSYNC__VALUE__ENABLED  0x1



#define AUD_PCMIN_IT_EN_SET 0x14

#define AUD_PCMIN_IT_EN_SET__OVF__SHIFT      0
#define AUD_PCMIN_IT_EN_SET__OVF__MASK       0x1
#define AUD_PCMIN_IT_EN_SET__OVF__VALUE__SET 0x1

#define AUD_PCMIN_IT_EN_SET__VSYNC__SHIFT      1
#define AUD_PCMIN_IT_EN_SET__VSYNC__MASK       0x1
#define AUD_PCMIN_IT_EN_SET__VSYNC__VALUE__SET 0x1



#define AUD_PCMIN_IT_EN_CLR 0x18

#define AUD_PCMIN_IT_EN_CLR__OVF__SHIFT        0
#define AUD_PCMIN_IT_EN_CLR__OVF__MASK         0x1
#define AUD_PCMIN_IT_EN_CLR__OVF__VALUE__CLEAR 0x1

#define AUD_PCMIN_IT_EN_CLR__VSYNC__SHIFT        1
#define AUD_PCMIN_IT_EN_CLR__VSYNC__MASK         0x1
#define AUD_PCMIN_IT_EN_CLR__VSYNC__VALUE__CLEAR 0x1



#define AUD_PCMIN_CTRL 0x1c

#define AUD_PCMIN_CTRL__MODE__SHIFT       0
#define AUD_PCMIN_CTRL__MODE__MASK        0x3
#define AUD_PCMIN_CTRL__MODE__VALUE__OFF  0x0
#define AUD_PCMIN_CTRL__MODE__VALUE__PCM  0x2
#define AUD_PCMIN_CTRL__MODE__VALUE__CD   0x3

#define AUD_PCMIN_CTRL__MEM_FMT__SHIFT                  2
#define AUD_PCMIN_CTRL__MEM_FMT__MASK                   0x1
#define AUD_PCMIN_CTRL__MEM_FMT__VALUE__16_BITS_0_BITS  0x0
#define AUD_PCMIN_CTRL__MEM_FMT__VALUE__16_BITS_16_BITS 0x1

#define AUD_PCMIN_CTRL__RND__SHIFT                   3
#define AUD_PCMIN_CTRL__RND__MASK                    0x1
#define AUD_PCMIN_CTRL__RND__VALUE__NO_ROUNDING      0x0
#define AUD_PCMIN_CTRL__RND__VALUE__16_BITS_ROUNDING 0x1

#define AUD_PCMIN_CTRL__NUM_FRAMES__SHIFT 4
#define AUD_PCMIN_CTRL__NUM_FRAMES__MASK  0xfffffff




#define AUD_PCMIN_STA 0x20

#define AUD_PCMIN_STA__RUN_STOP__SHIFT          0
#define AUD_PCMIN_STA__RUN_STOP__MASK           0x1
#define AUD_PCMIN_STA__RUN_STOP__VALUE__STOPPED 0x0
#define AUD_PCMIN_STA__RUN_STOP__VALUE__RUNNING 0x1

#define AUD_PCMIN_STA__OVF__SHIFT                    1
#define AUD_PCMIN_STA__OVF__MASK                     0x1
#define AUD_PCMIN_STA__OVF__VALUE__OVERFLOW_DETECTED 0x1

#define AUD_PCMIN_STA__SAMPL_CNT__SHIFT 2
#define AUD_PCMIN_STA__SAMPL_CNT__MASK  0xffff

#define AUD_PCMIN_STA__VSYNC__SHIFT 18
#define AUD_PCMIN_STA__VSYNC__MASK  0x1

#define AUD_PCMIN_STA__NFRAMES__SHIFT       19
#define AUD_PCMIN_STA__NFRAMES__MASK        0x1
#define AUD_PCMIN_STA__NFRAMES__VALUE__DONE 0x1



#define AUD_PCMIN_FMT 0x24

#define AUD_PCMIN_FMT__NBIT__SHIFT          0
#define AUD_PCMIN_FMT__NBIT__MASK           0x1
#define AUD_PCMIN_FMT__NBIT__VALUE__32_BITS 0x0
#define AUD_PCMIN_FMT__NBIT__VALUE__16_BITS 0x1

#define AUD_PCMIN_FMT__DATA_SIZE__SHIFT          1
#define AUD_PCMIN_FMT__DATA_SIZE__MASK           0x3
#define AUD_PCMIN_FMT__DATA_SIZE__VALUE__24_BITS 0x0
#define AUD_PCMIN_FMT__DATA_SIZE__VALUE__20_BITS 0x1
#define AUD_PCMIN_FMT__DATA_SIZE__VALUE__18_BITS 0x2
#define AUD_PCMIN_FMT__DATA_SIZE__VALUE__16_BITS 0x3

#define AUD_PCMIN_FMT__LR_POL__SHIFT            3
#define AUD_PCMIN_FMT__LR_POL__MASK             0x1
#define AUD_PCMIN_FMT__LR_POL__VALUE__LEFT_LOW  0x0
#define AUD_PCMIN_FMT__LR_POL__VALUE__LEFT_HIGH 0x1

#define AUD_PCMIN_FMT__SCLK_EDGE__SHIFT          4
#define AUD_PCMIN_FMT__SCLK_EDGE__MASK           0x1
#define AUD_PCMIN_FMT__SCLK_EDGE__VALUE__RISING  0x0
#define AUD_PCMIN_FMT__SCLK_EDGE__VALUE__FALLING 0x1

#define AUD_PCMIN_FMT__PADDING__SHIFT                5
#define AUD_PCMIN_FMT__PADDING__MASK                 0x1
#define AUD_PCMIN_FMT__PADDING__VALUE__1_CYCLE_DELAY 0x0
#define AUD_PCMIN_FMT__PADDING__VALUE__NO_DELAY      0x1

#define AUD_PCMIN_FMT__ALIGN__SHIFT        6
#define AUD_PCMIN_FMT__ALIGN__MASK         0x1
#define AUD_PCMIN_FMT__ALIGN__VALUE__RIGHT 0x0
#define AUD_PCMIN_FMT__ALIGN__VALUE__LEFT  0x1

#define AUD_PCMIN_FMT__ORDER__SHIFT            7
#define AUD_PCMIN_FMT__ORDER__MASK             0x1
#define AUD_PCMIN_FMT__ORDER__VALUE__LSB_FIRST 0x0
#define AUD_PCMIN_FMT__ORDER__VALUE__MSB_FIRST 0x1



#endif
