#ifndef __STM_REGISTERS_AUD_SPDIF_H
#define __STM_REGISTERS_AUD_SPDIF_H



#define AUD_SPDIF_RST 0x00

#define AUD_SPDIF_RST__SRSTP__SHIFT          0
#define AUD_SPDIF_RST__SRSTP__MASK           0x1
#define AUD_SPDIF_RST__SRSTP__VALUE__RUNNING 0x0
#define AUD_SPDIF_RST__SRSTP__VALUE__RESET   0x1



#define AUD_SPDIF_DATA 0x04

#define AUD_SPDIF_DATA__DATA__SHIFT 0
#define AUD_SPDIF_DATA__DATA__MASK  0xffffffff



#define AUD_SPDIF_ITS 0x08

#define AUD_SPDIF_ITS__UNF__SHIFT          0
#define AUD_SPDIF_ITS__UNF__MASK           0x1
#define AUD_SPDIF_ITS__UNF__VALUE__PENDING 0x1

#define AUD_SPDIF_ITS__EOBURST__SHIFT          1
#define AUD_SPDIF_ITS__EOBURST__MASK           0x1
#define AUD_SPDIF_ITS__EOBURST__VALUE__PENDING 0x1

#define AUD_SPDIF_ITS__EOBLOCK__SHIFT          2
#define AUD_SPDIF_ITS__EOBLOCK__MASK           0x1
#define AUD_SPDIF_ITS__EOBLOCK__VALUE__PENDING 0x1

#define AUD_SPDIF_ITS__EOLATENCY__SHIFT          3
#define AUD_SPDIF_ITS__EOLATENCY__MASK           0x1
#define AUD_SPDIF_ITS__EOLATENCY__VALUE__PENDING 0x1

#define AUD_SPDIF_ITS__EOPD__SHIFT          4
#define AUD_SPDIF_ITS__EOPD__MASK           0x1
#define AUD_SPDIF_ITS__EOPD__VALUE__PENDING 0x1

#define AUD_SPDIF_ITS__NSAMPLE__SHIFT          5
#define AUD_SPDIF_ITS__NSAMPLE__MASK           0x1
#define AUD_SPDIF_ITS__NSAMPLE__VALUE__PENDING 0x1



#define AUD_SPDIF_ITS_CLR 0x0c

#define AUD_SPDIF_ITS_CLR__UNF__SHIFT        0
#define AUD_SPDIF_ITS_CLR__UNF__MASK         0x1
#define AUD_SPDIF_ITS_CLR__UNF__VALUE__CLEAR 0x1

#define AUD_SPDIF_ITS_CLR__EOBURST__SHIFT        1
#define AUD_SPDIF_ITS_CLR__EOBURST__MASK         0x1
#define AUD_SPDIF_ITS_CLR__EOBURST__VALUE__CLEAR 0x1

#define AUD_SPDIF_ITS_CLR__EOBLOCK__SHIFT        2
#define AUD_SPDIF_ITS_CLR__EOBLOCK__MASK         0x1
#define AUD_SPDIF_ITS_CLR__EOBLOCK__VALUE__CLEAR 0x1

#define AUD_SPDIF_ITS_CLR__EOLATENCY__SHIFT        3
#define AUD_SPDIF_ITS_CLR__EOLATENCY__MASK         0x1
#define AUD_SPDIF_ITS_CLR__EOLATENCY__VALUE__CLEAR 0x1

#define AUD_SPDIF_ITS_CLR__EOPD__SHIFT        4
#define AUD_SPDIF_ITS_CLR__EOPD__MASK         0x1
#define AUD_SPDIF_ITS_CLR__EOPD__VALUE__CLEAR 0x1

#define AUD_SPDIF_ITS_CLR__NSAMPLE__SHIFT        5
#define AUD_SPDIF_ITS_CLR__NSAMPLE__MASK         0x1
#define AUD_SPDIF_ITS_CLR__NSAMPLE__VALUE__CLEAR 0x1



#define AUD_SPDIF_IT_EN 0x10

#define AUD_SPDIF_IT_EN__UNF__SHIFT           0
#define AUD_SPDIF_IT_EN__UNF__MASK            0x1
#define AUD_SPDIF_IT_EN__UNF__VALUE__DISABLED 0x0
#define AUD_SPDIF_IT_EN__UNF__VALUE__ENABLED  0x1

#define AUD_SPDIF_IT_EN__EOBURST__SHIFT           1
#define AUD_SPDIF_IT_EN__EOBURST__MASK            0x1
#define AUD_SPDIF_IT_EN__EOBURST__VALUE__DISABLED 0x0
#define AUD_SPDIF_IT_EN__EOBURST__VALUE__ENABLED  0x1

#define AUD_SPDIF_IT_EN__EOBLOCK__SHIFT           2
#define AUD_SPDIF_IT_EN__EOBLOCK__MASK            0x1
#define AUD_SPDIF_IT_EN__EOBLOCK__VALUE__DISABLED 0x0
#define AUD_SPDIF_IT_EN__EOBLOCK__VALUE__ENABLED  0x1

#define AUD_SPDIF_IT_EN__EOLATENCY__SHIFT           3
#define AUD_SPDIF_IT_EN__EOLATENCY__MASK            0x1
#define AUD_SPDIF_IT_EN__EOLATENCY__VALUE__DISABLED 0x0
#define AUD_SPDIF_IT_EN__EOLATENCY__VALUE__ENABLED 0x1

#define AUD_SPDIF_IT_EN__EOPD__SHIFT           4
#define AUD_SPDIF_IT_EN__EOPD__MASK            0x1
#define AUD_SPDIF_IT_EN__EOPD__VALUE__DISABLED 0x0
#define AUD_SPDIF_IT_EN__EOPD__VALUE__ENABLED  0x1

#define AUD_SPDIF_IT_EN__NSAMPLE__SHIFT           5
#define AUD_SPDIF_IT_EN__NSAMPLE__MASK            0x1
#define AUD_SPDIF_IT_EN__NSAMPLE__VALUE__DISABLED 0x0
#define AUD_SPDIF_IT_EN__NSAMPLE__VALUE__ENABLED  0x1



#define AUD_SPDIF_IT_EN_SET 0x14

#define AUD_SPDIF_IT_EN_SET__UNF__SHIFT      0
#define AUD_SPDIF_IT_EN_SET__UNF__MASK       0x1
#define AUD_SPDIF_IT_EN_SET__UNF__VALUE__SET 0x1

#define AUD_SPDIF_IT_EN_SET__EOBURST__SHIFT      1
#define AUD_SPDIF_IT_EN_SET__EOBURST__MASK       0x1
#define AUD_SPDIF_IT_EN_SET__EOBURST__VALUE__SET 0x1

#define AUD_SPDIF_IT_EN_SET__EOBLOCK__SHIFT      2
#define AUD_SPDIF_IT_EN_SET__EOBLOCK__MASK       0x1
#define AUD_SPDIF_IT_EN_SET__EOBLOCK__VALUE__SET 0x1

#define AUD_SPDIF_IT_EN_SET__EOLATENCY__SHIFT      3
#define AUD_SPDIF_IT_EN_SET__EOLATENCY__MASK       0x1
#define AUD_SPDIF_IT_EN_SET__EOLATENCY__VALUE__SET 0x1

#define AUD_SPDIF_IT_EN_SET__EOPD__SHIFT      4
#define AUD_SPDIF_IT_EN_SET__EOPD__MASK       0x1
#define AUD_SPDIF_IT_EN_SET__EOPD__VALUE__SET 0x1

#define AUD_SPDIF_IT_EN_SET__NSAMPLE__SHIFT      5
#define AUD_SPDIF_IT_EN_SET__NSAMPLE__MASK       0x1
#define AUD_SPDIF_IT_EN_SET__NSAMPLE__VALUE__SET 0x1



#define AUD_SPDIF_IT_EN_CLR 0x18

#define AUD_SPDIF_IT_EN_CLR__UNF__SHIFT        0
#define AUD_SPDIF_IT_EN_CLR__UNF__MASK         0x1
#define AUD_SPDIF_IT_EN_CLR__UNF__VALUE__CLEAR 0x1

#define AUD_SPDIF_IT_EN_CLR__EOBURST__SHIFT        1
#define AUD_SPDIF_IT_EN_CLR__EOBURST__MASK         0x1
#define AUD_SPDIF_IT_EN_CLR__EOBURST__VALUE__CLEAR 0x1

#define AUD_SPDIF_IT_EN_CLR__EOBLOCK__SHIFT        2
#define AUD_SPDIF_IT_EN_CLR__EOBLOCK__MASK         0x1
#define AUD_SPDIF_IT_EN_CLR__EOBLOCK__VALUE__CLEAR 0x1

#define AUD_SPDIF_IT_EN_CLR__EOLATENCY__SHIFT        3
#define AUD_SPDIF_IT_EN_CLR__EOLATENCY__MASK         0x1
#define AUD_SPDIF_IT_EN_CLR__EOLATENCY__VALUE__CLEAR 0x1

#define AUD_SPDIF_IT_EN_CLR__EOPD__SHIFT        4
#define AUD_SPDIF_IT_EN_CLR__EOPD__MASK         0x1
#define AUD_SPDIF_IT_EN_CLR__EOPD__VALUE__CLEAR 0x1

#define AUD_SPDIF_IT_EN_CLR__NSAMPLE__SHIFT        5
#define AUD_SPDIF_IT_EN_CLR__NSAMPLE__MASK         0x1
#define AUD_SPDIF_IT_EN_CLR__NSAMPLE__VALUE__CLEAR 0x1



#define AUD_SPDIF_CTRL 0x1c

#define AUD_SPDIF_CTRL__MODE__SHIFT                    0
#define AUD_SPDIF_CTRL__MODE__MASK                     0x7
#define AUD_SPDIF_CTRL__MODE__VALUE__OFF               0x0
#define AUD_SPDIF_CTRL__MODE__VALUE__MUTE_PCM_NULL     0x1
#define AUD_SPDIF_CTRL__MODE__VALUE__MUTE_PAUSE_BURSTS 0x2
#define AUD_SPDIF_CTRL__MODE__VALUE__PCM               0x3
#define AUD_SPDIF_CTRL__MODE__VALUE__ENCODED           0x4

#define AUD_SPDIF_CTRL__IDLE__SHIFT         3
#define AUD_SPDIF_CTRL__IDLE__MASK          0x1
#define AUD_SPDIF_CTRL__IDLE__VALUE__NORMAL 0x0
#define AUD_SPDIF_CTRL__IDLE__VALUE__IDLE   0x1

#define AUD_SPDIF_CTRL__RND__SHIFT                   4
#define AUD_SPDIF_CTRL__RND__MASK                    0x1
#define AUD_SPDIF_CTRL__RND__VALUE__NO_ROUNDING      0x0
#define AUD_SPDIF_CTRL__RND__VALUE__16_BITS_ROUNDING 0x1

#define AUD_SPDIF_CTRL__CLK_DIV__SHIFT 5
#define AUD_SPDIF_CTRL__CLK_DIV__MASK  0xff

#define AUD_SPDIF_CTRL__STUFFING__SHIFT           14
#define AUD_SPDIF_CTRL__STUFFING__MASK            0x1
#define AUD_SPDIF_CTRL__STUFFING__VALUE__SOFTWARE 0x0
#define AUD_SPDIF_CTRL__STUFFING__VALUE__HARDWARE 0x1

#define AUD_SPDIF_CTRL__MEMREAD__SHIFT 15
#define AUD_SPDIF_CTRL__MEMREAD__MASK  0x1ffff



#define AUD_SPDIF_STA 0x20

#define AUD_SPDIF_STA__RUN_STOP__SHIFT          0
#define AUD_SPDIF_STA__RUN_STOP__MASK           0x1
#define AUD_SPDIF_STA__RUN_STOP__VALUE__STOPPED 0x0
#define AUD_SPDIF_STA__RUN_STOP__VALUE__RUNNING 0x1

#define AUD_SPDIF_STA__UNF__SHIFT           1
#define AUD_SPDIF_STA__UNF__MASK            0x1
#define AUD_SPDIF_STA__UNF__VALUE__DETECTED 0x1

#define AUD_SPDIF_STA__EOBURST__SHIFT      2
#define AUD_SPDIF_STA__EOBURST__MASK       0x1
#define AUD_SPDIF_STA__EOBURST__VALUE__END 0x1

#define AUD_SPDIF_STA__EOBLOCK__SHIFT      3
#define AUD_SPDIF_STA__EOBLOCK__MASK       0x1
#define AUD_SPDIF_STA__EOBLOCK__VALUE__END 0x1

#define AUD_SPDIF_STA__EOLATENCY__SHIFT                         4
#define AUD_SPDIF_STA__EOLATENCY__MASK                          0x1
#define AUD_SPDIF_STA__EOLATENCY__VALUE__END_OF_LATENCY_COUNTER 0x1

#define AUD_SPDIF_STA__PDDATA__SHIFT       5
#define AUD_SPDIF_STA__PDDATA__MASK        0x1
#define AUD_SPDIF_STA__PDDATA__VALUE__SENT 0x1

#define AUD_SPDIF_STA__NSAMPLE__SHIFT       6
#define AUD_SPDIF_STA__NSAMPLE__MASK        0x1
#define AUD_SPDIF_STA__NSAMPLE__VALUE__DONE 0x1

#define AUD_SPDIF_STA__PABIT__SHIFT       7
#define AUD_SPDIF_STA__PABIT__MASK        0xff

#define AUD_SPDIF_STA__PDPAUSE__SHIFT       5
#define AUD_SPDIF_STA__PDPAUSE__MASK        0x1
#define AUD_SPDIF_STA__PDPAUSE__VALUE__SENT 0x1



#define AUD_SPDIF_PA_PB 0x24

#define AUD_SPDIF_PA_PB__PB__SHIFT 0
#define AUD_SPDIF_PA_PB__PB__MASK  0xffff

#define AUD_SPDIF_PA_PB__PA__SHIFT 16
#define AUD_SPDIF_PA_PB__PA__MASK  0xffff



#define AUD_SPDIF_PC_PD 0x28

#define AUD_SPDIF_PC_PD__PD__SHIFT 0
#define AUD_SPDIF_PC_PD__PD__MASK  0xffff

#define AUD_SPDIF_PC_PD__PC__SHIFT 16
#define AUD_SPDIF_PC_PD__PC__MASK  0xffff




#define AUD_SPDIF_CL1 0x2c

#define AUD_SPDIF_CL1__CL1__SHIFT 0
#define AUD_SPDIF_CL1__CL1__MASK  0xffffffff



#define AUD_SPDIF_CR1 0x30

#define AUD_SPDIF_CR1__CR1__SHIFT 0
#define AUD_SPDIF_CR1__CR1__MASK  0xffffffff



#define AUD_SPDIF_CL2_CR2_UV 0x34

#define AUD_SPDIF_CL2_CR2_UV__CL2__SHIFT 0
#define AUD_SPDIF_CL2_CR2_UV__CL2__MASK  0xf

#define AUD_SPDIF_CL2_CR2_UV__CR2__SHIFT 8
#define AUD_SPDIF_CL2_CR2_UV__CR2__MASK  0xf

#define AUD_SPDIF_CL2_CR2_UV__RV__SHIFT  16
#define AUD_SPDIF_CL2_CR2_UV__RV__MASK   0x1

#define AUD_SPDIF_CL2_CR2_UV__RU__SHIFT  17
#define AUD_SPDIF_CL2_CR2_UV__RU__MASK   0x1

#define AUD_SPDIF_CL2_CR2_UV__LV__SHIFT  18
#define AUD_SPDIF_CL2_CR2_UV__LV__MASK   0x1

#define AUD_SPDIF_CL2_CR2_UV__LU__SHIFT  19
#define AUD_SPDIF_CL2_CR2_UV__LU__MASK   0x1



#define AUD_SPDIF_PAU_LAT 0x38

#define AUD_SPDIF_PAU_LAT__LAT__SHIFT 0
#define AUD_SPDIF_PAU_LAT__LAT__MASK  0xffff

#define AUD_SPDIF_PAU_LAT__NPD_BURST__SHIFT 16
#define AUD_SPDIF_PAU_LAT__NPD_BURST__MASK  0xffff



#define AUD_SPDIF_BST_FL 0x3c

#define AUD_SPDIF_BST_FL__DBURST__SHIFT 0
#define AUD_SPDIF_BST_FL__DBURST__MASK  0xffff

#define AUD_SPDIF_BST_FL__PDBURST__SHIFT 16
#define AUD_SPDIF_BST_FL__PDBURST__MASK  0xffff

#endif
