#ifndef __STM_REGISTERS_AUD_SPDIFPC_H
#define __STM_REGISTERS_AUD_SPDIFPC_H



#define AUD_SPDIFPC_CFG 0x000

#define AUD_SPDIFPC_CFG__DEVICE_EN__SHIFT           0
#define AUD_SPDIFPC_CFG__DEVICE_EN__MASK            0x1
#define AUD_SPDIFPC_CFG__DEVICE_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_CFG__DEVICE_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_CFG__SW_RESET__SHIFT          1
#define AUD_SPDIFPC_CFG__SW_RESET__MASK           0x1
#define AUD_SPDIFPC_CFG__SW_RESET__VALUE__RUNNING 0x0
#define AUD_SPDIFPC_CFG__SW_RESET__VALUE__RESET   0x1

#define AUD_SPDIFPC_CFG__FIFO_EN__SHIFT           2
#define AUD_SPDIFPC_CFG__FIFO_EN__MASK            0x1
#define AUD_SPDIFPC_CFG__FIFO_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_CFG__FIFO_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_CFG__AUDIO_WORD_SIZE__SHIFT          3
#define AUD_SPDIFPC_CFG__AUDIO_WORD_SIZE__MASK           0x3
#define AUD_SPDIFPC_CFG__AUDIO_WORD_SIZE__VALUE__16_BITS 0x0
#define AUD_SPDIFPC_CFG__AUDIO_WORD_SIZE__VALUE__20_BITS 0x1
#define AUD_SPDIFPC_CFG__AUDIO_WORD_SIZE__VALUE__24_BITS 0x2

#define AUD_SPDIFPC_CFG__REQ_ACK_EN__SHIFT           5
#define AUD_SPDIFPC_CFG__REQ_ACK_EN__MASK            0x1
#define AUD_SPDIFPC_CFG__REQ_ACK_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_CFG__REQ_ACK_EN__VALUE__ENABLED  0x1

/* Undocumented configuration bit, which exists in some hardware... */
#define AUD_SPDIFPC_CFG__CHA_STA_BITS__SHIFT           6
#define AUD_SPDIFPC_CFG__CHA_STA_BITS__MASK            0x1
#define AUD_SPDIFPC_CFG__CHA_STA_BITS__VALUE__SUBFRAME 0x0
#define AUD_SPDIFPC_CFG__CHA_STA_BITS__VALUE__FRAME    0x1



#define AUD_SPDIFPC_STA 0x004

#define AUD_SPDIFPC_STA__SOFT_RESET__SHIFT         1
#define AUD_SPDIFPC_STA__SOFT_RESET__MASK          0x1
#define AUD_SPDIFPC_STA__SOFT_RESET__VALUE__ACTIVE 0x1

#define AUD_SPDIFPC_STA__VALIDITY_REG_EMPTY__SHIFT        2
#define AUD_SPDIFPC_STA__VALIDITY_REG_EMPTY__MASK         0x1
#define AUD_SPDIFPC_STA__VALIDITY_REG_EMPTY__VALUE__EMPTY 0x1

#define AUD_SPDIFPC_STA__VALIDITY_REG_UNDERRUN__SHIFT           3
#define AUD_SPDIFPC_STA__VALIDITY_REG_UNDERRUN__MASK            0x1
#define AUD_SPDIFPC_STA__VALIDITY_REG_UNDERRUN__VALUE__DETECTED 0x1

#define AUD_SPDIFPC_STA__USER_DATA_REG_STATUS__SHIFT        4
#define AUD_SPDIFPC_STA__USER_DATA_REG_STATUS__MASK         0x1
#define AUD_SPDIFPC_STA__USER_DATA_REG_STATUS__VALUE__EMPTY 0x1

#define AUD_SPDIFPC_STA__USER_DATA_REG_UNDERRUN__SHIFT           5
#define AUD_SPDIFPC_STA__USER_DATA_REG_UNDERRUN__MASK            0x1
#define AUD_SPDIFPC_STA__USER_DATA_REG_UNDERRUN__VALUE__DETECTED 0x1

#define AUD_SPDIFPC_STA__CHL_STS_BUFF_EMPTY__SHIFT        6
#define AUD_SPDIFPC_STA__CHL_STS_BUFF_EMPTY__MASK         0x1
#define AUD_SPDIFPC_STA__CHL_STS_BUFF_EMPTY__VALUE__EMPTY 0x1

#define AUD_SPDIFPC_STA__CHL_STS_BUFF_UNDERRUN__SHIFT           7
#define AUD_SPDIFPC_STA__CHL_STS_BUFF_UNDERRUN__MASK            0x1
#define AUD_SPDIFPC_STA__CHL_STS_BUFF_UNDERRUN__VALUE__DETECTED 0x1

#define AUD_SPDIFPC_STA__I2S_FIFO_OVERRUN__SHIFT           8
#define AUD_SPDIFPC_STA__I2S_FIFO_OVERRUN__MASK            0x1
#define AUD_SPDIFPC_STA__I2S_FIFO_OVERRUN__VALUE__DETECTED 0x1

#define AUD_SPDIFPC_STA__CURR_CHL_STS_BUFFER__SHIFT       16
#define AUD_SPDIFPC_STA__CURR_CHL_STS_BUFFER__SHIFT__MASK 0x7



#define AUD_SPDIFPC_IT_EN 0x008

#define AUD_SPDIFPC_IT_EN__INTERRUPT_EN__SHIFT           0
#define AUD_SPDIFPC_IT_EN__INTERRUPT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__INTERRUPT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__INTERRUPT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__SOFT_RESET_INT_EN__SHIFT           1
#define AUD_SPDIFPC_IT_EN__SOFT_RESET_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__SOFT_RESET_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__SOFT_RESET_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__VALIDITY_EMPTY_INT_EN__SHIFT           2
#define AUD_SPDIFPC_IT_EN__VALIDITY_EMPTY_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__VALIDITY_EMPTY_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__VALIDITY_EMPTY_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__VALIDITY_UNDERRUN_INT_EN__SHIFT           3
#define AUD_SPDIFPC_IT_EN__VALIDITY_UNDERRUN_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__VALIDITY_UNDERRUN_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__VALIDITY_UNDERRUN_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__USER_DATA_EMPTY_INT_EN__SHIFT           4
#define AUD_SPDIFPC_IT_EN__USER_DATA_EMPTY_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__USER_DATA_EMPTY_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__USER_DATA_EMPTY_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__USER_DATA_UNDERRUN_INT_EN__SHIFT           5
#define AUD_SPDIFPC_IT_EN__USER_DATA_UNDERRUN_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__USER_DATA_UNDERRUN_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__USER_DATA_UNDERRUN_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__CHL_STS_EMPTY_INT_EN__SHIFT           6
#define AUD_SPDIFPC_IT_EN__CHL_STS_EMPTY_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__CHL_STS_EMPTY_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__CHL_STS_EMPTY_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__CHL_STS_UNDERRUN_INT_EN__SHIFT           7
#define AUD_SPDIFPC_IT_EN__CHL_STS_UNDERRUN_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__CHL_STS_UNDERRUN_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__CHL_STS_UNDERRUN_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__I2S_FIFO_OVERRUN_INT_EN__SHIFT           8
#define AUD_SPDIFPC_IT_EN__I2S_FIFO_OVERRUN_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__I2S_FIFO_OVERRUN_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__I2S_FIFO_OVERRUN_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__RUN_STOP_INT_EN__SHIFT           16
#define AUD_SPDIFPC_IT_EN__RUN_STOP_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__RUN_STOP_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__RUN_STOP_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__UNDERFLOW_INT_EN__SHIFT           17
#define AUD_SPDIFPC_IT_EN__UNDERFLOW_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__UNDERFLOW_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__UNDERFLOW_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__EODATABURST_INT_EN__SHIFT           18
#define AUD_SPDIFPC_IT_EN__EODATABURST_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__EODATABURST_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__EODATABURST_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__EOBLOCK_INT_EN__SHIFT           19
#define AUD_SPDIFPC_IT_EN__EOBLOCK_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__EOBLOCK_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__EOBLOCK_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__LATENCY_INT_EN__SHIFT           20
#define AUD_SPDIFPC_IT_EN__LATENCY_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__LATENCY_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__LATENCY_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__PD_DATA_BURST__SHIFT           21
#define AUD_SPDIFPC_IT_EN__PD_DATA_BURST__MASK            0x1
#define AUD_SPDIFPC_IT_EN__PD_DATA_BURST__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__PD_DATA_BURST__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__SAMPLES_READ_INT_EN__SHIFT           22
#define AUD_SPDIFPC_IT_EN__SAMPLES_READ_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__SAMPLES_READ_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__SAMPLES_READ_INT_EN__VALUE__ENABLED  0x1

#define AUD_SPDIFPC_IT_EN__PD_PAUSE_BURST_INT_EN__SHIFT           31
#define AUD_SPDIFPC_IT_EN__PD_PAUSE_BURST_INT_EN__MASK            0x1
#define AUD_SPDIFPC_IT_EN__PD_PAUSE_BURST_INT_EN__VALUE__DISABLED 0x0
#define AUD_SPDIFPC_IT_EN__PD_PAUSE_BURST_INT_EN__VALUE__ENABLED  0x1



#define AUD_SPDIFPC_ITS 0x00c

#define AUD_SPDIFPC_ITS__INTERRUPT__SHIFT          0
#define AUD_SPDIFPC_ITS__INTERRUPT__MASK           0x1
#define AUD_SPDIFPC_ITS__INTERRUPT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__SOFT_RESET_INT__SHIFT          1
#define AUD_SPDIFPC_ITS__SOFT_RESET_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__SOFT_RESET_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__VALIDITY_EMPTY_INT__SHIFT          2
#define AUD_SPDIFPC_ITS__VALIDITY_EMPTY_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__VALIDITY_EMPTY_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__VALIDITY_UNDERRUN_INT__SHIFT          3
#define AUD_SPDIFPC_ITS__VALIDITY_UNDERRUN_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__VALIDITY_UNDERRUN_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__USER_DATA_EMPTY_INT__SHIFT          4
#define AUD_SPDIFPC_ITS__USER_DATA_EMPTY_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__USER_DATA_EMPTY_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__USER_DATA_UNDERRUN_INT__SHIFT          5
#define AUD_SPDIFPC_ITS__USER_DATA_UNDERRUN_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__USER_DATA_UNDERRUN_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__CHL_STS_EMPTY_INT__SHIFT          6
#define AUD_SPDIFPC_ITS__CHL_STS_EMPTY_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__CHL_STS_EMPTY_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__CHL_STS_UNDERRUN_INT__SHIFT          7
#define AUD_SPDIFPC_ITS__CHL_STS_UNDERRUN_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__CHL_STS_UNDERRUN_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__I2S_FIFO_OVERRUN_INT__SHIFT          8
#define AUD_SPDIFPC_ITS__I2S_FIFO_OVERRUN_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__I2S_FIFO_OVERRUN_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__RUN_STOP_INT__SHIFT          16
#define AUD_SPDIFPC_ITS__RUN_STOP_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__RUN_STOP_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__UNDERFLOW_INT__SHIFT          17
#define AUD_SPDIFPC_ITS__UNDERFLOW_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__UNDERFLOW_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__EODATABURST_INT__SHIFT          18
#define AUD_SPDIFPC_ITS__EODATABURST_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__EODATABURST_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__EOBLOCK_INT__SHIFT          19
#define AUD_SPDIFPC_ITS__EOBLOCK_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__EOBLOCK_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__LATENCY_INT__SHIFT          20
#define AUD_SPDIFPC_ITS__LATENCY_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__LATENCY_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__PD_DATA_BURST__SHIFT          21
#define AUD_SPDIFPC_ITS__PD_DATA_BURST__MASK           0x1
#define AUD_SPDIFPC_ITS__PD_DATA_BURST__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__SAMPLES_READ_INT__SHIFT          22
#define AUD_SPDIFPC_ITS__SAMPLES_READ_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__SAMPLES_READ_INT__VALUE__PENDING 0x1

#define AUD_SPDIFPC_ITS__PD_PAUSE_BURST_INT__SHIFT          31
#define AUD_SPDIFPC_ITS__PD_PAUSE_BURST_INT__MASK           0x1
#define AUD_SPDIFPC_ITS__PD_PAUSE_BURST_INT__VALUE__PENDING 0x1



#define AUD_SPDIFPC_IT_CLR 0x010

#define AUD_SPDIFPC_IT_CLR__INTERRUPT_EN__SHIFT        0
#define AUD_SPDIFPC_IT_CLR__INTERRUPT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__INTERRUPT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__SOFT_RESET_INT_EN__SHIFT        1
#define AUD_SPDIFPC_IT_CLR__SOFT_RESET_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__SOFT_RESET_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__VALIDITY_EMPTY_INT_EN__SHIFT        2
#define AUD_SPDIFPC_IT_CLR__VALIDITY_EMPTY_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__VALIDITY_EMPTY_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__VALIDITY_UNDERRUN_INT_EN__SHIFT        3
#define AUD_SPDIFPC_IT_CLR__VALIDITY_UNDERRUN_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__VALIDITY_UNDERRUN_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__USER_DATA_EMPTY_INT_EN__SHIFT        4
#define AUD_SPDIFPC_IT_CLR__USER_DATA_EMPTY_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__USER_DATA_EMPTY_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__USER_DATA_UNDERRUN_INT_EN__SHIFT        5
#define AUD_SPDIFPC_IT_CLR__USER_DATA_UNDERRUN_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__USER_DATA_UNDERRUN_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__CHL_STS_EMPTY_INT_EN__SHIFT        6
#define AUD_SPDIFPC_IT_CLR__CHL_STS_EMPTY_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__CHL_STS_EMPTY_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__CHL_STS_UNDERRUN_INT_EN__SHIFT        7
#define AUD_SPDIFPC_IT_CLR__CHL_STS_UNDERRUN_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__CHL_STS_UNDERRUN_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__I2S_FIFO_OVERRUN_INT_EN__SHIFT        8
#define AUD_SPDIFPC_IT_CLR__I2S_FIFO_OVERRUN_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__I2S_FIFO_OVERRUN_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__RUN_STOP_INT_EN__SHIFT        16
#define AUD_SPDIFPC_IT_CLR__RUN_STOP_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__RUN_STOP_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__UNDERFLOW_INT_EN__SHIFT        17
#define AUD_SPDIFPC_IT_CLR__UNDERFLOW_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__UNDERFLOW_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__EODATABURST_INT_EN__SHIFT        18
#define AUD_SPDIFPC_IT_CLR__EODATABURST_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__EODATABURST_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__EOBLOCK_INT_EN__SHIFT        19
#define AUD_SPDIFPC_IT_CLR__EOBLOCK_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__EOBLOCK_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__LATENCY_INT_EN__SHIFT        20
#define AUD_SPDIFPC_IT_CLR__LATENCY_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__LATENCY_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__PD_DATA_BURST__SHIFT        21
#define AUD_SPDIFPC_IT_CLR__PD_DATA_BURST__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__PD_DATA_BURST__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__SAMPLES_READ_INT_EN__SHIFT        22
#define AUD_SPDIFPC_IT_CLR__SAMPLES_READ_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__SAMPLES_READ_INT_EN__VALUE__CLEAR 0x1

#define AUD_SPDIFPC_IT_CLR__PD_PAUSE_BURST_INT_EN__SHIFT        31
#define AUD_SPDIFPC_IT_CLR__PD_PAUSE_BURST_INT_EN__MASK         0x1
#define AUD_SPDIFPC_IT_CLR__PD_PAUSE_BURST_INT_EN__VALUE__CLEAR 0x1



#define AUD_SPDIFPC_VAL 0x100

#define AUD_SPDIFPC_VAL__VALIDITY_BITS__SHIFT 0
#define AUD_SPDIFPC_VAL__VALIDITY_BITS__MASK  0xffffffff



#define AUD_SPDIFPC_DATA 0x104

#define AUD_SPDIFPC_DATA__USER_DATA_BITS__SHIFT 0
#define AUD_SPDIFPC_DATA__USER_DATA_BITS__MASK  0xffffffff



#define AUD_SPDIFPC_CHA_STA(n) (0x108 + (n) * 4)

#define AUD_SPDIFPC_CHA_STA__CHA_STA__SHIFT 0
#define AUD_SPDIFPC_CHA_STA__CHA_STA__MASK  0xffffffff



#define AUD_SPDIFPC_CTRL 0x200

#define AUD_SPDIFPC_CTRL__OPERATION__SHIFT                    0
#define AUD_SPDIFPC_CTRL__OPERATION__MASK                     0x7
#define AUD_SPDIFPC_CTRL__OPERATION__VALUE__OFF               0x0
#define AUD_SPDIFPC_CTRL__OPERATION__VALUE__MUTE_PCM_NULL     0x1
#define AUD_SPDIFPC_CTRL__OPERATION__VALUE__MUTE_PAUSE_BURSTS 0x2
#define AUD_SPDIFPC_CTRL__OPERATION__VALUE__PCM               0x3
#define AUD_SPDIFPC_CTRL__OPERATION__VALUE__ENCODED           0x4

#define AUD_SPDIFPC_CTRL__IDLE_STATE__SHIFT         3
#define AUD_SPDIFPC_CTRL__IDLE_STATE__MASK          0x1
#define AUD_SPDIFPC_CTRL__IDLE_STATE__VALUE__NORMAL 0x0
#define AUD_SPDIFPC_CTRL__IDLE_STATE__VALUE__IDLE   0x1

#define AUD_SPDIFPC_CTRL__ROUNDING__SHIFT                   4
#define AUD_SPDIFPC_CTRL__ROUNDING__MASK                    0x1
#define AUD_SPDIFPC_CTRL__ROUNDING__VALUE__NO_ROUNDING      0x0
#define AUD_SPDIFPC_CTRL__ROUNDING__VALUE__16_BITS_ROUNDING 0x1

#define AUD_SPDIFPC_CTRL__DIVIDER__SHIFT 5
#define AUD_SPDIFPC_CTRL__DIVIDER__MASK  0xff

#define AUD_SPDIFPC_CTRL__STUFFING__SHIFT           14
#define AUD_SPDIFPC_CTRL__STUFFING__MASK            0x1
#define AUD_SPDIFPC_CTRL__STUFFING__VALUE__SOFTWARE 0x0
#define AUD_SPDIFPC_CTRL__STUFFING__VALUE__HARDWARE 0x1

#define AUD_SPDIFPC_CTRL__NO_SAMPLES__SHIFT 15
#define AUD_SPDIFPC_CTRL__NO_SAMPLES__MASK  0x1ffff



#define AUD_SPDIFPC_SPDIFSTA 0x204

#define AUD_SPDIFPC_SPDIFSTA__RUN_STOP__SHIFT          0
#define AUD_SPDIFPC_SPDIFSTA__RUN_STOP__MASK           0x1
#define AUD_SPDIFPC_SPDIFSTA__RUN_STOP__VALUE__STOPPED 0x0
#define AUD_SPDIFPC_SPDIFSTA__RUN_STOP__VALUE__RUNNING 0x1

#define AUD_SPDIFPC_SPDIFSTA__UNDERFLOW__SHIFT           1
#define AUD_SPDIFPC_SPDIFSTA__UNDERFLOW__MASK            0x1
#define AUD_SPDIFPC_SPDIFSTA__UNDERFLOW__VALUE__DETECTED 0x1

#define AUD_SPDIFPC_SPDIFSTA__EODATABURST__SHIFT      2
#define AUD_SPDIFPC_SPDIFSTA__EODATABURST__MASK       0x1
#define AUD_SPDIFPC_SPDIFSTA__EODATABURST__VALUE__END 0x1

#define AUD_SPDIFPC_SPDIFSTA__EOBLOCK__SHIFT      3
#define AUD_SPDIFPC_SPDIFSTA__EOBLOCK__MASK       0x1
#define AUD_SPDIFPC_SPDIFSTA__EOBLOCK__VALUE__END 0x1

#define AUD_SPDIFPC_SPDIFSTA__LATENCY__SHIFT                         4
#define AUD_SPDIFPC_SPDIFSTA__LATENCY__MASK                          0x1
#define AUD_SPDIFPC_SPDIFSTA__LATENCY__VALUE__END_OF_LATENCY_COUNTER 0x1

#define AUD_SPDIFPC_SPDIFSTA__PD_DATABURST__SHIFT       5
#define AUD_SPDIFPC_SPDIFSTA__PD_DATABURST__MASK        0x1
#define AUD_SPDIFPC_SPDIFSTA__PD_DATABURST__VALUE__SENT 0x1

#define AUD_SPDIFPC_SPDIFSTA__AUDIO_READ__SHIFT       6
#define AUD_SPDIFPC_SPDIFSTA__AUDIO_READ__MASK        0x1
#define AUD_SPDIFPC_SPDIFSTA__AUDIO_READ__VALUE__DONE 0x1

#define AUD_SPDIFPC_SPDIFSTA__PA_C_BIT_NUMBER__SHIFT       7
#define AUD_SPDIFPC_SPDIFSTA__PA_C_BIT_NUMBER__MASK        0xff

#define AUD_SPDIFPC_SPDIFSTA__PD_PAUSEBURST__SHIFT       5
#define AUD_SPDIFPC_SPDIFSTA__PD_PAUSEBURST__MASK        0x1
#define AUD_SPDIFPC_SPDIFSTA__PD_PAUSEBURST__VALUE__SENT 0x1



#define AUD_SPDIFPC_PAUSE 0x208

#define AUD_SPDIFPC_PAUSE__PAUSE_LENGTH__SHIFT 0
#define AUD_SPDIFPC_PAUSE__PAUSE_LENGTH__MASK  0xffff

#define AUD_SPDIFPC_PAUSE__PAUSE_LAT__SHIFT 16
#define AUD_SPDIFPC_PAUSE__PAUSE_LAT__MASK  0xffff



#define AUD_SPDIFPC_DATA_BURST 0x20c

#define AUD_SPDIFPC_DATA_BURST__DATA_BURST__SHIFT 0
#define AUD_SPDIFPC_DATA_BURST__DATA_BURST__MASK  0xffff

#define AUD_SPDIFPC_DATA_BURST__PAUSE_BURST__SHIFT 16
#define AUD_SPDIFPC_DATA_BURST__PAUSE_BURST__MASK  0xffff



#define AUD_SPDIFPC_PA_PB 0x210

#define AUD_SPDIFPC_PA_PB__PB__SHIFT 0
#define AUD_SPDIFPC_PA_PB__PB__MASK  0xffff

#define AUD_SPDIFPC_PA_PB__PA__SHIFT 16
#define AUD_SPDIFPC_PA_PB__PA__MASK  0xffff



#define AUD_SPDIFPC_PC_PD 0x214

#define AUD_SPDIFPC_PC_PD__PD__SHIFT 0
#define AUD_SPDIFPC_PC_PD__PD__MASK  0xffff

#define AUD_SPDIFPC_PC_PD__PC__SHIFT 16
#define AUD_SPDIFPC_PC_PD__PC__MASK  0xffff




#define AUD_SPDIFPC_CL1 0x218

#define AUD_SPDIFPC_CL1__CHANNEL_STATUS__SHIFT 0
#define AUD_SPDIFPC_CL1__CHANNEL_STATUS__MASK  0xffffffff



#define AUD_SPDIFPC_CR1 0x21c

#define AUD_SPDIFPC_CR1__CH_STA__SHIFT 0
#define AUD_SPDIFPC_CR1__CH_STA__MASK  0xffffffff



#define AUD_SPDIFPC_SUV 0x220

#define AUD_SPDIFPC_SUV__CH_STA_LEFT__SHIFT 0
#define AUD_SPDIFPC_SUV__CH_STA_LEFT__MASK  0xf

#define AUD_SPDIFPC_SUV__CH_STA_RIGHT__SHIFT 8
#define AUD_SPDIFPC_SUV__CH_STA_RIGHT__MASK  0xf

#define AUD_SPDIFPC_SUV__DATA_LEFT__SHIFT  16
#define AUD_SPDIFPC_SUV__DATA_LEFT__MASK   0x1

#define AUD_SPDIFPC_SUV__DATA_RIGHT__SHIFT  17
#define AUD_SPDIFPC_SUV__DATA_RIGHT__MASK   0x1

#define AUD_SPDIFPC_SUV__VAL_LEFT__SHIFT  18
#define AUD_SPDIFPC_SUV__VAL_LEFT__MASK   0x1

#define AUD_SPDIFPC_SUV__VAL_RIGHT__SHIFT  19
#define AUD_SPDIFPC_SUV__VAL_RIGHT__MASK   0x1

#endif
