#ifndef __STM_REGISTERS_AUDCFG_FSYN_H
#define __STM_REGISTERS_AUDCFG_FSYN_H



#define AUDCFG_FSYN_CFG 0x00

#define AUDCFG_FSYN_CFG__RSTP__SHIFT          0
#define AUDCFG_FSYN_CFG__RSTP__MASK           0x1
#define AUDCFG_FSYN_CFG__RSTP__VALUE__RUNNING 0x0
#define AUDCFG_FSYN_CFG__RSTP__VALUE__RESET   0x1

#define AUDCFG_FSYN_CFG__PCM_CLK_SEL__SHIFT 2
#define AUDCFG_FSYN_CFG__PCM_CLK_SEL__MASK  0xf
/* Inverted in 7200 vs 710x - madness, isn't it? :-O */
#ifdef CONFIG_CPU_SUBTYPE_STB7100
#define AUDCFG_FSYN_CFG__PCM_CLK_SEL__VALUE__EXTCLK(n) (0 << n)
#define AUDCFG_FSYN_CFG__PCM_CLK_SEL__VALUE__FSYNTH(n) (1 << n)
#endif
#ifdef CONFIG_CPU_SUBTYPE_STX7200
#define AUDCFG_FSYN_CFG__PCM_CLK_SEL__VALUE__FSYNTH(n) (0 << n)
#define AUDCFG_FSYN_CFG__PCM_CLK_SEL__VALUE__EXTCLK(n) (1 << n)
#endif

/* Doesn't exist in 7200 - again, veeery strange... */
#ifdef CONFIG_CPU_SUBTYPE_STB7100
#define AUDCFG_FSYN_CFG__FS_EN__SHIFT              6
#define AUDCFG_FSYN_CFG__FS_EN__MASK               0x7
#define AUDCFG_FSYN_CFG__FS_EN__VALUE__DISABLED(n) (0 << n)
#define AUDCFG_FSYN_CFG__FS_EN__VALUE__ENABLED(n)  (1 << n)
#endif

#define AUDCFG_FSYN_CFG__NSB__SHIFT             10
#define AUDCFG_FSYN_CFG__NSB__MASK              0xf
#define AUDCFG_FSYN_CFG__NSB__VALUE__STANDBY(n) (0 << n)
#define AUDCFG_FSYN_CFG__NSB__VALUE__ACTIVE(n)  (1 << n)

#define AUDCFG_FSYN_CFG__NPDA__SHIFT             14
#define AUDCFG_FSYN_CFG__NPDA__MASK              0x1
#define AUDCFG_FSYN_CFG__NPDA__VALUE__POWER_DOWN 0x0
#define AUDCFG_FSYN_CFG__NPDA__VALUE__NORMAL     0x1

#define AUDCFG_FSYN_CFG__NDIV__SHIFT            15
#define AUDCFG_FSYN_CFG__NDIV__MASK             0x1
#define AUDCFG_FSYN_CFG__NDIV__VALUE__27_30_MHZ 0x0
#define AUDCFG_FSYN_CFG__NDIV__VALUE__54_60_MHZ 0x1

#define AUDCFG_FSYN_CFG__BW_SEL__SHIFT                      16
#define AUDCFG_FSYN_CFG__BW_SEL__MASK                       0x3
#define AUDCFG_FSYN_CFG__BW_SEL__VALUE__VERY_GOOD_REFERENCE 0x0
#define AUDCFG_FSYN_CFG__BW_SEL__VALUE__GOOD_REFERENCE      0x1
#define AUDCFG_FSYN_CFG__BW_SEL__VALUE__BAD_REFERENCE       0x2
#define AUDCFG_FSYN_CFG__BW_SEL__VALUE__VERY_BAD_REFERENCE  0x3

#if CONFIG_CPU_SUBTYPE_STX7200
#define AUDCFG_FSYN_CFG__TST_CLK_SEL__SHIFT 18
#define AUDCFG_FSYN_CFG__TST_CLK_SEL__MASK  0x3
#endif

#if CONFIG_CPU_SUBTYPE_STX7200
#define AUDCFG_FSYN_CFG__TST_PCMDAT__SHIFT 20
#define AUDCFG_FSYN_CFG__TST_PCMDAT__MASK  0xf
#endif

#ifdef CONFIG_CPU_SUBTYPE_STB7100
#define AUDCFG_FSYN_CFG__REF_CLK_IN__SHIFT               23
#endif
#if CONFIG_CPU_SUBTYPE_STX7200
#define AUDCFG_FSYN_CFG__REF_CLK_IN__SHIFT               24
#endif
#define AUDCFG_FSYN_CFG__REF_CLK_IN__MASK                0x1
#define AUDCFG_FSYN_CFG__REF_CLK_IN__VALUE__30_MHZ_CLOCK 0x0
#define AUDCFG_FSYN_CFG__REF_CLK_IN__VALUE__SYSBCLKINALT 0x1



#define AUDCFG_FSYN_MD(n) ((n + 1) * 0x10 + 0x00)

#define AUDCFG_FSYN_MD__MD__SHIFT 0
#define AUDCFG_FSYN_MD__MD__MASK  0x1f



#define AUDCFG_FSYN_PE(n) ((n + 1) * 0x10 + 0x04)

#define AUDCFG_FSYN_PE__PE__SHIFT 0
#define AUDCFG_FSYN_PE__PE__MASK  0xffff



#define AUDCFG_FSYN_SDIV(n) ((n + 1) * 0x10 + 0x08)

#define AUDCFG_FSYN_SDIV__SDIV__SHIFT 0
#define AUDCFG_FSYN_SDIV__SDIV__MASK  0x7



#define AUDCFG_FSYN_PROGEN(n) ((n + 1) * 0x10 + 0x0c)

#define AUDCFG_FSYN_PROGEN__PROG_EN__SHIFT                  0
#define AUDCFG_FSYN_PROGEN__PROG_EN__MASK                   0x1
#define AUDCFG_FSYN_PROGEN__PROG_EN__VALUE__PE0_MD0_IGNORED 0x0
#define AUDCFG_FSYN_PROGEN__PROG_EN__VALUE__PE0_MD0_USED    0x1




#endif
