#ifndef __STM_REGISTERS_AUDCFG_ADAC_H
#define __STM_REGISTERS_AUDCFG_ADAC_H



#define AUDCFG_ADAC_CTRL 0x00

#define AUDCFG_ADAC_CTRL__NRST__SHIFT         0
#define AUDCFG_ADAC_CTRL__NRST__MASK          0x1
#define AUDCFG_ADAC_CTRL__NRST__VALUE__RESET  0x0
#define AUDCFG_ADAC_CTRL__NRST__VALUE__NORMAL 0x1

#define AUDCFG_ADAC_CTRL__MODE__SHIFT          1
#define AUDCFG_ADAC_CTRL__MODE__MASK           0x3
#define AUDCFG_ADAC_CTRL__MODE__VALUE__DEFAULT 0x0

#define AUDCFG_ADAC_CTRL__NSB__SHIFT             3
#define AUDCFG_ADAC_CTRL__NSB__MASK              0x1
#define AUDCFG_ADAC_CTRL__NSB__VALUE__POWER_DOWN 0x0
#define AUDCFG_ADAC_CTRL__NSB__VALUE__NORMAL     0x1

#define AUDCFG_ADAC_CTRL__SOFTMUTE__SHIFT         4
#define AUDCFG_ADAC_CTRL__SOFTMUTE__MASK          0x1
#define AUDCFG_ADAC_CTRL__SOFTMUTE__VALUE__NORMAL 0x0
#define AUDCFG_ADAC_CTRL__SOFTMUTE__VALUE__MUTE   0x1

#define AUDCFG_ADAC_CTRL__PDNANA__SHIFT             5
#define AUDCFG_ADAC_CTRL__PDNANA__MASK              0x1
#define AUDCFG_ADAC_CTRL__PDNANA__VALUE__POWER_DOWN 0x0
#define AUDCFG_ADAC_CTRL__PDNANA__VALUE__NORMAL     0x1

#define AUDCFG_ADAC_CTRL__PDNBG__SHIFT             6
#define AUDCFG_ADAC_CTRL__PDNBG__MASK              0x1
#define AUDCFG_ADAC_CTRL__PDNBG__VALUE__POWER_DOWN 0x0
#define AUDCFG_ADAC_CTRL__PDNBG__VALUE__NORMAL     0x1



#endif
