#ifndef __STM_REGISTERS_STX7200_AUDCFG_H
#define __STM_REGISTERS_STX7200_AUDCFG_H



#define AUDCFG_IOMUX_CTRL 0x00

#define AUDCFG_IOMUX_CTRL__PCM_CLK_EN__SHIFT         0
#define AUDCFG_IOMUX_CTRL__PCM_CLK_EN__MASK          0x1
#define AUDCFG_IOMUX_CTRL__PCM_CLK_EN__VALUE__INPUT  0x1
#define AUDCFG_IOMUX_CTRL__PCM_CLK_EN__VALUE__OUTPUT 0x0

#define AUDCFG_IOMUX_CTRL__DATA0_EN__SHIFT         1
#define AUDCFG_IOMUX_CTRL__DATA0_EN__MASK          0x1
#define AUDCFG_IOMUX_CTRL__DATA0_EN__VALUE__INPUT  0x0
#define AUDCFG_IOMUX_CTRL__DATA0_EN__VALUE__OUTPUT 0x1

#define AUDCFG_IOMUX_CTRL__DATA1_EN__SHIFT         2
#define AUDCFG_IOMUX_CTRL__DATA1_EN__MASK          0x1
#define AUDCFG_IOMUX_CTRL__DATA1_EN__VALUE__INPUT  0x0
#define AUDCFG_IOMUX_CTRL__DATA1_EN__VALUE__OUTPUT 0x1

#define AUDCFG_IOMUX_CTRL__DATA2_EN__SHIFT         3
#define AUDCFG_IOMUX_CTRL__DATA2_EN__MASK          0x1
#define AUDCFG_IOMUX_CTRL__DATA2_EN__VALUE__INPUT  0x0
#define AUDCFG_IOMUX_CTRL__DATA2_EN__VALUE__OUTPUT 0x1

#define AUDCFG_IOMUX_CTRL__SPDIF_EN__SHIFT          4
#define AUDCFG_IOMUX_CTRL__SPDIF_EN__MASK           0x1
#define AUDCFG_IOMUX_CTRL__SPDIF_EN__VALUE__DISABLE 0x0
#define AUDCFG_IOMUX_CTRL__SPDIF_EN__VALUE__ENABLE  0x1



#define AUDCFG_HDMI_CTRL 0x04

#define AUDCFG_HDMI_CTRL__HDMI_DEBUG__SHIFT              0
#define AUDCFG_HDMI_CTRL__HDMI_DEBUG__MASK               0x1
#define AUDCFG_HDMI_CTRL__HDMI_DEBUG__VALUE__PCM_PLAYERS 0x0
#define AUDCFG_HDMI_CTRL__HDMI_DEBUG__VALUE__HDMI        0x1

#define AUDCFG_HDMI_CTRL__HDMI_SPDIF__SHIFT       1
#define AUDCFG_HDMI_CTRL__HDMI_SPDIF__MASK        0x1
#define AUDCFG_HDMI_CTRL__HDMI_SPDIF__VALUE_PCM   0x0
#define AUDCFG_HDMI_CTRL__HDMI_SPDIF__VALUE_SPDIF 0x1



#define AUDCFG_RECOVERY_CTRL 0x08

#define AUDCFG_RECOVERY_CTRL__RECO_EN0__SHIFT 0
#define AUDCFG_RECOVERY_CTRL__RECO_EN0__MASK  0x1

#define AUDCFG_RECOVERY_CTRL__RECO_SEL0__SHIFT       1
#define AUDCFG_RECOVERY_CTRL__RECO_SEL0__MASK        0x3
#define AUDCFG_RECOVERY_CTRL__RECO_SEL0__VALUE__CLK0 0x0
#define AUDCFG_RECOVERY_CTRL__RECO_SEL0__VALUE__CLK1 0x1
#define AUDCFG_RECOVERY_CTRL__RECO_SEL0__VALUE__CLK2 0x2
#define AUDCFG_RECOVERY_CTRL__RECO_SEL0__VALUE__CLK3 0x3

#define AUDCFG_RECOVERY_CTRL__RECO_EXT0__SHIFT 3
#define AUDCFG_RECOVERY_CTRL__RECO_EXT0__MASK  0x1

#define AUDCFG_RECOVERY_CTRL__RECO_EN1__SHIFT 4
#define AUDCFG_RECOVERY_CTRL__RECO_EN1__MASK  0x1

#define AUDCFG_RECOVERY_CTRL__RECO_SEL1__SHIFT       5
#define AUDCFG_RECOVERY_CTRL__RECO_SEL1__MASK        0x3
#define AUDCFG_RECOVERY_CTRL__RECO_SEL1__VALUE__CLK0 0x0
#define AUDCFG_RECOVERY_CTRL__RECO_SEL1__VALUE__CLK1 0x1
#define AUDCFG_RECOVERY_CTRL__RECO_SEL1__VALUE__CLK2 0x2
#define AUDCFG_RECOVERY_CTRL__RECO_SEL1__VALUE__CLK3 0x3

#define AUDCFG_RECOVERY_CTRL__RECO_EXT1__SHIFT 7
#define AUDCFG_RECOVERY_CTRL__RECO_EXT1__MASK  0x1



#endif
